---
#
experiment_wide:
    fullscreen: false
    show_progress_bar: true
    images_to_preload:
         - 'static/stimuli/img/aardvark.png'
         - 'static/stimuli/img/bat.png'
         - 'static/stimuli/img/alligator.png'
         - 'static/stimuli/img/blimp.png'
         - 'static/stimuli/img/Eals01.png'
         - 'static/stimuli/img/Eals02.png'
# ----------------------------- INSTRUCTIONS PARAMETERS --------------------------------------------- #
#
# all instructions are jspsych 'instructions' trial types, which takes a few paramters available to all
# jspysch plugins (see http://docs.jspsych.org/plugins/overview/#parameters-available-in-all-plugins)
# namely 'timing_post_trial' and 'data' as well as a few parameters available specifically to the
# instructions plugin (see http://docs.jspsych.org/plugins/jspsych-instructions/#parameters)
#
instructions:
    #
    # the MAIN INSTRUCTIONS at the begining of the experiment
    #
    main:
        timing_post_trial: 0
        data: {phase: 'instructions_main'}
        pages:
            - "<h1 class='center-content'>Welcome</h1><p class='center-content'>Welcome to the experiment. Press next to continue.</p>"
            - "<h1 class='center-content'>Instructions</h1><p class='center-content'>In this experiment, you will be asked to categorize objects or expressions one at a time.</p>"
            - >
                <h1 class='center-content'>Instructions</h1>
                <p class='center-content'>The experiment is broken up into three parts.  In each part,
                you will categorize a different type of object or expression.  Each part will take no longer than 2 minutes.</p>
        key_forward: 'rightarrow'
        key_backward: 'leftarrow'
        allow_backward: true
        allow_keys: true
        show_clickable_nav: true
    #
    # the INCIDENTAL EXPOSURE INSTRUCTIONS (before incidental_exposure phase)
    #
    incidental_exposure:
        timing_post_trial: 1000
        data: {phase: 'instructions_incidental_exposure'}
        pages:
            - >
                <h1 class='center-content'>Part 1 of 3</h1>
                <h4 class='center-content'>Please read these instructions carefully</h4>
                <p class='center-content'>You will see different pictures, one at a time.
                Some of the pictures are of real objects, and some are of made-up objects.
                Your job is to decide if the thing in the picture is a real object or not.</p>
                <p class='center-content'>If it is real, press 1. If it is not, press 2.</p>
                <p class='center-content'>We're measuring how long it takes you to answer, so answer as soon as possible.
                If you aren't sure, just press the button for the first answer you think of.</p>
                <h4 class='center-content'>Press spacebar when you are ready to start</h4>
        key_forward: 'spacebar'
        key_backward: 'leftarrow'
        allow_backward: false
        allow_keys: true
        show_clickable_nav: false
    #
    # the MATH TASK INSTRUCTIONS (before math_task phase)
    #
    math_task:
        timing_post_trial: 1000
        data: {phase: 'instructions_math_task'}
        pages:
            - >
                <h1 class='center-content'>Part 2 of 3</h1>
                <h4 class='center-content'>Please read these instructions carefully</h4>
                <p class='center-content'>Now you will see some math problems, one at a time.
                Some of the math problems are true and some are not.
                Your job is to decide if the math problem is true or false.</p>
                <p class='center-content'>If it is true, press 1. If it is false, press 2.</p>
                <p class='center-content'>We're measuring how long it takes you to answer, so answer as soon as possible.
                If you aren't sure, just press the button for the first answer you think of.</p>
                <h4 class='center-content'>Press spacebar when you are ready to start</h4>
        key_forward: 'spacebar'
        key_backward: 'leftarrow'
        allow_backward: false
        allow_keys: true
        show_clickable_nav: false
    #
    # the MEMORY TASK INSTRUCTIONS at the begining of the experiment
    #
    memory_task:
        timing_post_trial: 1000
        data: {phase: 'instructions_memory_task'}
        pages:
            - >
                <h1 class='center-content'>Part 3 of 3</h1>
                <h4 class='center-content'>Please read these instructions carefully</h4>
                <p class='center-content'>Now you will see more pictures, one at a time.
                Some of the pictures are ones you just saw and some are new.
                Your job is to decide if the picture is old or new.</p>
                <p class='center-content'>If it is old, press 1. If it is new, press 2.</p>
                <p class='center-content'>We're measuring how long it takes you to answer, so answer as soon as possible.
                If you aren't sure, just press the button for the first answer you think of.</p>
                <h4 class='center-content'>Press spacebar when you are ready to start</h4>
        key_forward: 'spacebar'
        key_backward: 'leftarrow'
        allow_backward: false
        allow_keys: true
        show_clickable_nav: false
    thanks_screen:
        timing_post_trial: 1000
        data: {phase: 'thanks_screen'}
        pages:
            - "<h2 class='center-content'>Thanks for participating!</h2><p class='center-content'>Phillip, you can press spacebar to see the data that gets stored.</p>"
        key_forward: 'spacebar'
        key_backward: 'leftarrow'
        allow_backward: false
        allow_keys: true
        show_clickable_nav: false
#
# ----------------------------- INCIDENTAL EXPOSURE PARAMETERS --------------------------------------------- #
#
# incidental_exposure is a jspsych 'categorize' trial type, which takes a timeline parameter that includes
# the list of stimuli, specified below as 'timeline'. (see http://docs.jspsych.org/plugins/jspsych-categorize/)
#
incidental_exposure:
    #
    # Here we set a few parameters available to all jspsych plugins
    # (see http://docs.jspsych.org/plugins/overview/#parameters-available-in-all-plugins)
    #
    timing_post_trial: 1000
    data: {phase: 'incidental_exposure'}

    # show_prompt_during_ISI: true
    # show_stimulus_during_ISI: true
    # isi_stimulus_is_html: true
    # isi_stimulus: 'static/stimuli/img/aardvark.png'
    # isi_prompt:
    #
    # Here we set a few parameters available to the 'categorize' jspsych plugin
    # These parameters apply to ALL trials in incidental_exposure
    # (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    prompt: "<p class='center-content'>Press 1 for real and 2 for made-up</p>"
    choices:
        - '1'
        - '2'
    correct_text: "<p class='center-content'>Correct</p>"
    incorrect_text: "<p class='center-content'>Wrong</p>"
    force_correct_button_press: false
    show_stim_with_feedback: true
    show_feedback_on_timeout: false
    timeout_message: "<p class='center-content'>Please respond faster</p>"
    timing_stim: -1
    timing_feedback_duration: 2000
    timing_response: 1500
    response_ends_trial: true
    #
    # Here we set further parameters available to the incidental_exposure timeline
    # (randomize_order is true or false depending on whether you want the timeline (trial presentation) to be randomized)
    # In the timeline, we set a few parameters that are avialble to the 'categorize' jsych plugin
    # that we want to change on each trial.  (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    randomize_order: true
    timeline:
        - {stimulus: 'static/stimuli/img/aardvark.png', is_html: false, key_answer: '1', data: {this_stim: 'aardvark'}}
        - {stimulus: 'static/stimuli/img/blimp.png', is_html: false, key_answer: '1', data: {this_stim: 'blimp'}}
        - {stimulus: 'static/stimuli/img/Eals01.png', is_html: false, key_answer: '2', data: {this_stim: 'Eals01'}}
        - {stimulus: 'static/stimuli/img/Eals02.png', is_html: false, key_answer: '2', data: {this_stim: 'Eals02'}}
#
# ----------------------------- MATH TASK PARAMETERS --------------------------------------------- #
#
# math_task is a jspsych 'categorize' trial type, which takes a timeline parameter that includes
# the list of stimuli, specified below as 'timeline'. (see http://docs.jspsych.org/plugins/jspsych-categorize/)
#
math_task:
    #
    # Here we set a few parameters available to all jspsych plugins
    # (see http://docs.jspsych.org/plugins/overview/#parameters-available-in-all-plugins)
    #
    timing_post_trial: 1000
    data: {phase: 'math_task'}
    #
    # Here we set a few parameters available to the 'categorize' jspsych plugin
    # These parameters apply to ALL trials in incidental_exposure
    # (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    prompt: "<p class='center-content'>Press 1 for True and 2 for False</p>"
    choices:
        - 49
        - 50
    correct_text: "<p class='center-content'>Correct</p>"
    incorrect_text: "<p class='center-content'>Wrong</p>"
    force_correct_button_press: false
    show_stim_with_feedback: true
    show_feedback_on_timeout: false
    timeout_message: "<p class='center-content'>Please respond faster</p>"
    timing_stim: -1
    timing_feedback_duration: 2000
    timing_response: 2000
    response_ends_trial: true
    #
    # Here we set further parameters available to the math_task timeline
    # (randomize_order is true or false depending on whether you want the timeline (trial presentation) to be randomized)
    # In the timeline, we set a few parameters that are avialble to the 'categorize' jsych plugin
    # that we want to change on each trial.  (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    randomize_order: true
    timeline:
        - {stimulus: "<h1 class='center-content'>1 + 1 = 2</h1>", is_html: true, key_answer: 49, data: {this_stim: "1 + 1 = 2"}}
        - {stimulus: "<h1 class='center-content'>3 + 1 = 2</h1>", is_html: true, key_answer: 50, data: {this_stim: "3 + 1 = 2"}}
        - {stimulus: "<h1 class='center-content'>-1 + 5 = 2</h1>", is_html: true, key_answer: 50, data: {this_stim: "-1 + 5 = 2"}}
        - {stimulus: "<h1 class='center-content'>4 - 2 = 2</h1>", is_html: true, key_answer: 49, data: {this_stim: "4 - 2 = 2"}}
#
# ----------------------------- MEMORY TASK PARAMETERS --------------------------------------------- #
#
# memory_task is a jspsych 'categorize' trial type, which takes a timeline parameter that includes
# the list of stimuli, specified below as 'timeline'. (see http://docs.jspsych.org/plugins/jspsych-categorize/)
#
memory_task:
    #
    # Here we set a few parameters available to all jspsych plugins
    # (see http://docs.jspsych.org/plugins/overview/#parameters-available-in-all-plugins)
    #
    timing_post_trial: 1000
    data: {phase: 'math_task'}
    #
    # Here we set a few parameters available to the 'categorize' jspsych plugin
    # These parameters apply to ALL trials in memory_task
    # (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    prompt: "<p class='center-content'>Press 1 for old and 2 for new</p>"
    choices:
        - 49
        - 50
    correct_text: "<p class='center-content'>Correct</p>"
    incorrect_text: "<p class='center-content'>Wrong</p>"
    force_correct_button_press: false
    show_stim_with_feedback: true
    show_feedback_on_timeout: false
    timeout_message: "<p class='center-content'>Please respond faster</p>"
    timing_stim: -1
    timing_feedback_duration: 2000
    timing_response: 1500
    response_ends_trial: true
    is_html: false
    #
    # Here we set further parameters available to the memory_task timeline
    # (randomize_order is true or false depending on whether you want the timeline (trial presentation) to be randomized)
    # In the timeline, we set a few parameters that are avialble to the 'categorize' jsych plugin
    # that we want to change on each trial.  (see http://docs.jspsych.org/plugins/jspsych-categorize/#parameters)
    #
    randomize_order: true
    timeline:
        - {stimulus: 'static/stimuli/img/aardvark.png', is_html: false, key_answer: 49, data: {this_stim: 'aardvark'}}
        - {stimulus: 'static/stimuli/img/blimp.png', is_html: false, key_answer: 49, data: {this_stim: 'blimp'}}
        - {stimulus: 'static/stimuli/img/alligator.png', is_html: false, key_answer: 50, data: {this_stim: 'Eals01'}}
        - {stimulus: 'static/stimuli/img/bat.png', is_html: false, key_answer: 50, data: {this_stim: 'Eals02'}}
#
# ----------------------------- DEMOGRAPHIC QUESTIONS PARAMETERS --------------------------------------------- #
#
# demographics_questions is a jspsych 'categorize' trial type, which takes a timeline parameter that includes
# the list of questions you want to ask, specified below as 'timeline'. (see http://docs.jspsych.org/plugins/jspsych-categorize/)
#
demographic_questions:
    preamble: "<p class='center-content'>For each question, select the answer that best describes you</p>"
    questions:
        - "Select the age group that describes you"
        - "Select your gender"
    options:
        - ["18-45", "45-100", "prefer not to respond"]
        - ["Female", "Male", "prefer not to respond"]
    required:
        - true
        - true
    horizontal: false
debrief_questions:
    preamble: "<p class='center-content'>For each question, type in your response.</p>"
    questions:
        - "Did you notice anything about this task?"
        - "Do you have any feedback you want to provide?"
    rows:
        - 5
        - 3
    columns:
        - 50
        - 40
